### ISSUE TITLE
Cool done, plan to port light-theme for iTerm2?

### ISSUE THREAD

**Issue by MrWrh** [colepeters/base16-spacemacs-redux#6]
For iTerm2, thank you 3000!!! 😄

And guys, you may find the light theme for vim [here](https://github.com/liuchengxu/space-vim-theme).

**Comment by colepeters** [comment]
Thanks for the interest. 😃
At the moment I sadly don't have the time available to create a light theme as well, but pull requests are always welcome.

(Closing this as it's a duplicate of #5)
